üîß Setting up environment...
üìã Environment verification:
Active environment: 
Python path: /home/nilkel/miniconda3/envs/zipnerf2/bin/python
PyTorch version: 2.7.1+cu128
CUDA available: True
GPU name: NVIDIA GeForce RTX 5090

üöÄ Starting ZipNeRF Potential+Triplane training...
üé¨ Scene: lego
üí¨ Comment: binocc_unfixedoptconf_nogate_noreg_5xconf_256res
üî≤ Binary Occupancy: False
‚è∞ Started at: Fri Jul 11 09:10:21 PM CEST 2025
üìÅ Data directory: /home/nilkel/Projects/data/nerf_synthetic/lego
üìã Config: configs/potential_triplane.gin

üíª Training command:
accelerate launch train.py --gin_configs=configs/potential_triplane.gin --gin_bindings="Config.data_dir = '/home/nilkel/Projects/data/nerf_synthetic/lego'" --gin_bindings="Config.debug_confidence_grid_path = ''" --gin_bindings="Config.freeze_debug_confidence = False" --gin_bindings="Config.binary_occupancy = False" --gin_bindings="Config.confidence_grid_resolution = (256, 256, 256)" --gin_bindings="Config.comment = 'binocc_unfixedoptconf_nogate_noreg_5xconf_256res'"

ipex flag is deprecated, will be removed in Accelerate v1.10. From 2.7.0, PyTorch has all needed optimizations for Intel CPU and XPU.
/home/nilkel/Projects/zipnerf-pytorch/gridencoder/grid.py:23: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, backend, inputs, embeddings, offsets, per_level_scale, base_resolution, calc_grad_inputs=False, gridtype=0, align_corners=False, interpolation=0):
/home/nilkel/Projects/zipnerf-pytorch/gridencoder/grid.py:66: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad):
/home/nilkel/Projects/zipnerf-pytorch/gridencoder/grid.py:179: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/home/nilkel/Projects/zipnerf-pytorch/gridencoder/grid.py:273: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
2025-07-11 21:10:27: Config(use_triplane=False, use_potential=True, confidence_grid_resolution=(256, 256, 256), confidence_reg_mult=0, binary_occupancy=False, debug_confidence_grid_path='', freeze_debug_confidence=False, dataset_loader='blender', batching='all_images', batch_size=4096, patch_size=1, factor=4, multiscale=False, multiscale_levels=4, forward_facing=False, render_path=False, llffhold=8, llff_use_all_images_for_training=False, llff_use_all_images_for_testing=False, use_tiffs=False, compute_disp_metrics=False, compute_normal_metrics=False, disable_multiscale_loss=False, randomized=True, near=2.0, far=6.0, exp_name='lego_potential_25000_0711_2110_binocc_unfixedoptconf_nogate_noreg_5xconf_256res', comment='binocc_unfixedoptconf_nogate_noreg_5xconf_256res', data_dir='/home/nilkel/Projects/data/nerf_synthetic/lego', vocab_tree_path=None, render_chunk_size=65536, num_showcase_images=5, deterministic_showcase=True, vis_num_rays=16, vis_decimate=0, use_wandb=True, wandb_project='my-nerf-experiments', wandb_entity=None, wandb_name='lego_potential_25000_0711_2110_binocc_unfixedoptconf_nogate_noreg_5xconf_256res', wandb_tags=None, wandb_notes=None, disable_tensorboard=False, dpcpp_backend=False, importance_sampling=False, max_steps=25000, early_exit_steps=None, checkpoint_every=5000, resume_from_checkpoint=True, no_wandb=False, checkpoints_total_limit=1, gradient_scaling=False, print_every=100, train_render_every=500, data_loss_type='charb', charb_padding=0.001, data_loss_mult=1.0, data_coarse_loss_mult=0.0, interlevel_loss_mult=0.0, anti_interlevel_loss_mult=0.01, orientation_loss_mult=0.0, orientation_coarse_loss_mult=0.0, orientation_loss_target='normals_pred', predicted_normal_loss_mult=0.0, predicted_normal_coarse_loss_mult=0.0, hash_decay_mults=10, lr_init=0.01, lr_final=0.001, lr_delay_steps=5000, lr_delay_mult=1e-08, confidence_lr_init=0.05, confidence_lr_final=0.005, confidence_lr_delay_steps=None, confidence_lr_delay_mult=None, confidence_lr_multiplier=1.0, adam_beta1=0.9, adam_beta2=0.99, adam_eps=1e-15, grad_max_norm=0.0, grad_max_val=0.0, distortion_loss_mult=0.005, opacity_loss_mult=0.0, eval_only_once=False, eval_save_output=True, eval_save_ray_data=False, eval_render_interval=1, eval_dataset_limit=2147483647, eval_quantize_metrics=True, eval_crop_borders=8, render_video_fps=60, render_video_crf=18, render_path_frames=120, z_variation=0.0, z_phase=0.0, render_dist_percentile=0.5, render_dist_curve_fn=<ufunc 'log'>, render_path_file=None, render_resolution=None, render_focal=None, render_camtype=None, render_spherical=False, render_save_async=True, render_spline_keyframes=None, render_spline_n_interp=30, render_spline_degree=5, render_spline_smoothness=0.03, render_spline_interpolate_exposure=False, rawnerf_mode=False, exposure_percentile=97.0, num_border_pixels_to_mask=0, apply_bayer_mask=False, autoexpose_renders=False, eval_raw_affine_cc=False, zero_glo=False, valid_weight_thresh=0.05, isosurface_threshold=20, mesh_voxels=134217728, visibility_resolution=512, mesh_radius=1.0, mesh_max_radius=10.0, std_value=0.0, compute_visibility=False, extract_visibility=True, decimate_target=-1, vertex_color=True, vertex_projection=True, tsdf_radius=2.0, tsdf_resolution=512, truncation_margin=5.0, tsdf_max_radius=10.0)
2025-07-11 21:10:27: Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

üîß Loading pretrained confidence grid from: 
2025-07-11 21:10:27: Error!
Traceback (most recent call last):
  File "/home/nilkel/Projects/zipnerf-pytorch/train.py", line 716, in <module>
    app.run(main)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/absl/app.py", line 316, in run
    _run_main(main, args)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/absl/app.py", line 261, in _run_main
    sys.exit(main(argv))
  File "/home/nilkel/Projects/zipnerf-pytorch/train.py", line 70, in main
    model = models.Model(config=config)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/nilkel/Projects/zipnerf-pytorch/internal/models.py", line 69, in __init__
    self.confidence_field = ConfidenceField(
  File "/home/nilkel/Projects/zipnerf-pytorch/internal/field.py", line 34, in __init__
    self._load_pretrained_grid(pretrained_grid_path, device)
  File "/home/nilkel/Projects/zipnerf-pytorch/internal/field.py", line 55, in _load_pretrained_grid
    pretrained_logits = torch.load(pretrained_grid_path, map_location='cpu')
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
  In call to configurable 'Model' (<class 'internal.models.Model'>) in scope 'train'
Traceback (most recent call last):
  File "/home/nilkel/miniconda3/envs/zipnerf2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1199, in launch_command
    simple_launcher(args)
  File "/home/nilkel/miniconda3/envs/zipnerf2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 785, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/nilkel/miniconda3/envs/zipnerf2/bin/python3.9', 'train.py', '--gin_configs=configs/potential_triplane.gin', "--gin_bindings=Config.data_dir = '/home/nilkel/Projects/data/nerf_synthetic/lego'", "--gin_bindings=Config.debug_confidence_grid_path = ''", '--gin_bindings=Config.freeze_debug_confidence = False', '--gin_bindings=Config.binary_occupancy = False', '--gin_bindings=Config.confidence_grid_resolution = (256, 256, 256)', "--gin_bindings=Config.comment = 'binocc_unfixedoptconf_nogate_noreg_5xconf_256res'"]' returned non-zero exit status 1.

‚úÖ Training completed successfully!
‚è∞ Finished at: Fri Jul 11 09:10:28 PM CEST 2025
üìÑ Full log: ./tmux_logs/training_pt_lego_binocc_unfixedoptconf_nogate_noreg_5xconf_256res_0711_211013.log
üìÅ Check results in: exp/

‚ùå Training failed at line 76. Check logs: ./tmux_logs/training_pt_lego_binocc_unfixedoptconf_nogate_noreg_5xconf_256res_0711_211013.log
